/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class TcpClient {
  constructor(libPath: string)
  create(): void
  send(id: number, msg: string): void
  disconnect(id: number): void
  cleanup(): void
  setMessageHandler(cb: any): void
  getSystemInfo(): [number, string, string]
  connect(portal: string, host: string, port: string, callback: (arg0: string, arg1: string) => number): number
}
